"""
Auto-generate command reference documentation from Discord bot cogs.
Run this script to regenerate docs/generated/commands-*.md from bot/cogs/*.py.
"""
from __future__ import annotations

import ast
import re
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
COGS_DIR = REPO_ROOT / "bot" / "cogs"
DOCS_DIR = REPO_ROOT / "docs" / "generated"
DOCS_DIR.mkdir(parents=True, exist_ok=True)


def extract_commands(filepath: Path) -> list[dict]:
    """Parse a cog file and extract all commands with their docstrings and signatures."""
    text = filepath.read_text(encoding="utf-8")
    tree = ast.parse(text)
    commands = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.AsyncFunctionDef):
            continue
        # Look for @commands.command(name=...) decorators
        cmd_name = None
        for dec in node.decorator_list:
            if isinstance(dec, ast.Call):
                if getattr(dec.func, "attr", None) == "command":
                    for kw in dec.keywords:
                        if kw.arg == "name":
                            cmd_name = ast.literal_eval(kw.value)
                    if cmd_name is None and dec.args:
                        cmd_name = ast.literal_eval(dec.args[0])
            elif isinstance(dec, ast.Attribute) and dec.attr == "command":
                cmd_name = None  # use function name
        if not cmd_name:
            continue
        # Parse docstring
        docstring = ast.get_docstring(node) or ""
        # Parse permissions
        perms = []
        for dec in node.decorator_list:
            if isinstance(dec, ast.Call):
                if getattr(dec.func, "attr", None) in ("has_permissions", "has_guild_permissions"):
                    for kw in dec.keywords:
                        if isinstance(kw.value, ast.Constant) and kw.value.value is True:
                            perms.append(kw.arg)
        # Arguments after ctx
        args = []
        for arg in node.args.args[1:]:
            # Skip 'ctx' — it's internal
            arg_name = arg.arg
            if arg_name == "ctx":
                continue
            arg_type = ""
            if arg.annotation:
                arg_type = ast.unparse(arg.annotation) if hasattr(ast, "unparse") else str(arg.annotation)
            # Default value
            def_offset = len(node.args.args) - len(node.args.defaults)
            arg_index = node.args.args.index(arg)
            default = None
            if arg_index >= def_offset:
                def_val_idx = arg_index - def_offset
                if def_val_idx < len(node.args.defaults):
                    try:
                        default = ast.literal_eval(node.args.defaults[def_val_idx])
                    except Exception:
                        pass
            if default is not None:
                args.append(f"{arg_name}: {arg_type} = {default}" if arg_type else f"{arg_name} = {default}")
            else:
                args.append(f"{arg_name}: {arg_type}" if arg_type else arg_name)
        # Extract description from docstring (first line)
        desc = docstring.split("\n")[0].strip() if docstring else ""
        usage_line = docstring.split("Usage:")[1].split("\n")[0].strip() if "Usage:" in docstring else ""
        commands.append({
            "name": cmd_name,
            "description": desc,
            "permissions": perms,
            "arguments": args,
            "usage": usage_line,
            "docstring": docstring,
        })
    return commands


def render_command_doc(cog_name: str, commands: list[dict]) -> str:
    lines = [
        f"---",
        f"title: {cog_name.title()} Commands",
        f"description: Full command reference for the {cog_name} cog.",
        f"order: 1",
        f"tags: [commands, {cog_name}]",
        f"generated: true",
        f"---",
        f"",
        f"# {cog_name.title()} Commands",
        f"",
        f"These are all commands in the **{cog_name}** cog.\\",
        f"\u003e Autogenerated on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"",
        f"| Command | Arguments | Permissions | Description |",
        f"|---------|-----------|-------------|-------------|",
    ]
    for cmd in commands:
        args = " ".join(cmd["arguments"]) or "None"
        perms = ", ".join(cmd["permissions"]) or "—"
        lines.append(f"| `!{cmd['name']}` | {args} | {perms} | {cmd['description'][:80]} |")
    lines.append("")
    for cmd in commands:
        lines.append(f"## `!{cmd['name']}`")
        lines.append(f"")
        lines.append(f"**Permissions:** {', '.join(cmd['permissions']) or 'Any member'}")
        lines.append(f"")
        lines.append(f"**Syntax:** `!{cmd['name']}` {' '.join(cmd['arguments'])}")
        lines.append(f"")
        if cmd["docstring"]:
            lines.append(f"{cmd['docstring']}")
        else:
            lines.append("*No description available.*")
        lines.append(f"")
    return "\n".join(lines)


def main() -> None:
    for path in sorted(COGS_DIR.glob("*.py")):
        if path.name.startswith("_") or path.name == "skill_factory_bridge.py":
            continue
        cog_name = path.stem
        commands = extract_commands(path)
        if not commands:
            continue
        doc = render_command_doc(cog_name, commands)
        out_path = DOCS_DIR / f"commands-{cog_name}.md"
        out_path.write_text(doc, encoding="utf-8")
        print(f"Generated {out_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
