/**
 * Discord Bot Service
 * Manages Discord bot lifecycle, commands, and integration with Central Hub
 */

import { PrismaClient, DiscordBot } from '@prisma/client';
import { exec } from 'child_process';
import { promisify } from 'util';
import { writeFile, mkdir, rm } from 'fs/promises';
import path from 'path';
import { withDiscordCircuitBreaker } from '../utils/circuit-breaker';
import { withCache, CACHE_TTL } from './redis';

const prisma = new PrismaClient();
const execAsync = promisify(exec);

// Bot deployment directory
const BOTS_DIR = process.env.BOTS_DIR || './bots';

interface BotConfiguration {
  prefix?: string;
  adminRoles?: string[];
  logChannel?: string;
  welcomeChannel?: string;
  aiEnabled: boolean;
  moderationEnabled: boolean;
  customCommands: Array<{
    name: string;
    response: string;
  }>;
}

interface BotStatus {
  status: 'running' | 'stopped' | 'error' | 'restarting';
  pid?: number;
  uptime?: number;
  memoryUsage?: number;
  messageCount: number;
  errorCount: number;
  lastError?: string;
  guilds: Array<{
    id: string;
    name: string;
    memberCount: number;
  }>;
}

/**
 * Create a new Discord bot
 */
export async function createBot(
  name: string,
  token: string,
  config: Partial<BotConfiguration> = {}
): Promise<DiscordBot> {
  // Validate token by making a test request to Discord API (with circuit breaker)
  try {
    const botData = await withDiscordCircuitBreaker(async () => {
      const response = await fetch('https://discord.com/api/v10/users/@me', {
        headers: { 'Authorization': `Bot ${token}` },
      });

      if (!response.ok) {
        throw new Error('Invalid Discord bot token');
      }

      return await response.json();
    }) as any;

    // Create bot record
    const bot = await prisma.discordBot.create({
      data: {
        name,
        token, // In production, encrypt this
        clientId: botData.id,
        status: 'stopped',
        configuration: {
          prefix: '!',
          aiEnabled: true,
          moderationEnabled: true,
          customCommands: [],
          ...config,
        } as any,
        aiEnabled: config.aiEnabled ?? true,
      },
    });

    // Generate bot files
    await generateBotFiles(bot);

    console.log(`✅ Created Discord bot: ${name} (ID: ${bot.id})`);
    return bot;
  } catch (error) {
    console.error('❌ Failed to create bot:', error);
    throw error;
  }
}

/**
 * Generate bot files from template
 */
async function generateBotFiles(bot: DiscordBot): Promise<void> {
  const botDir = path.join(BOTS_DIR, bot.id);
  
  await mkdir(botDir, { recursive: true });

  // Generate package.json
  const packageJson = {
    name: `discord-bot-${bot.id}`,
    version: '1.0.0',
    description: bot.name,
    main: 'index.js',
    scripts: {
      start: 'node index.js',
      dev: 'nodemon index.js',
    },
    dependencies: {
      'discord.js': '^14.14.1',
      'axios': '^1.6.2',
      'dotenv': '^16.3.1',
      'express': '^4.18.2',
    },
  };

  await writeFile(
    path.join(botDir, 'package.json'),
    JSON.stringify(packageJson, null, 2)
  );

  // Generate main bot file
  const botCode = generateBotCode(bot);
  await writeFile(path.join(botDir, 'index.js'), botCode);

  // Generate .env file
  const envContent = `DISCORD_TOKEN=${bot.token}
BOT_ID=${bot.id}
CENTRAL_HUB_API_URL=${process.env.CENTRAL_HUB_API_URL || 'http://localhost:3001'}
OLLAMA_HOST=${process.env.OLLAMA_HOST || 'http://localhost:11434'}
AI_ENABLED=${bot.aiEnabled}
`;
  await writeFile(path.join(botDir, '.env'), envContent);

  // Generate command handlers
  await writeFile(
    path.join(botDir, 'commands.js'),
    generateCommandsCode(bot)
  );
}

/**
 * Generate the main bot code
 */
function generateBotCode(bot: DiscordBot): string {
  return `/**
 * Discord Bot: ${bot.name}
 * Generated by Central Hub
 * ID: ${bot.id}
 */

const { Client, GatewayIntentBits, Collection, Events } = require('discord.js');
const express = require('express');
const axios = require('axios');
require('dotenv').config();

// Bot configuration
const config = ${JSON.stringify(bot.configuration, null, 2)};

// Initialize Discord client
const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.GuildPresences,
  ],
});

// Command collection
client.commands = new Collection();

// Load commands
const { loadCommands } = require('./commands');
loadCommands(client);

// Health check server
const app = express();
app.use(express.json());

app.get('/health', (req, res) => {
  res.json({
    status: 'ok',
    bot: client.user?.tag || 'not ready',
    guilds: client.guilds.cache.size,
    uptime: process.uptime(),
    memory: process.memoryUsage(),
  });
});

// Central Hub webhook endpoint
app.post('/webhook', async (req, res) => {
  const { action, channelId, message } = req.body;
  
  try {
    const channel = await client.channels.fetch(channelId);
    if (channel && channel.isTextBased()) {
      await channel.send(message);
      res.json({ success: true });
    } else {
      res.status(404).json({ error: 'Channel not found' });
    }
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

app.listen(3000, () => {
  console.log('🌐 Health check server running on port 3000');
});

// Bot ready event
client.once(Events.ClientReady, async () => {
  console.log(\`🤖 Logged in as \${client.user.tag}\`);
  
  // Register slash commands
  const commands = [
    {
      name: 'help',
      description: 'Show help information',
    },
    {
      name: 'status',
      description: 'Show bot status',
    },
    {
      name: 'ask',
      description: 'Ask AI a question',
      options: [{
        name: 'question',
        type: 3, // STRING
        description: 'Your question',
        required: true,
      }],
    },
    {
      name: 'kick',
      description: 'Kick a user',
      options: [
        {
          name: 'user',
          type: 6, // USER
          description: 'User to kick',
          required: true,
        },
        {
          name: 'reason',
          type: 3,
          description: 'Reason for kick',
          required: false,
        },
      ],
    },
    {
      name: 'ban',
      description: 'Ban a user',
      options: [
        {
          name: 'user',
          type: 6,
          description: 'User to ban',
          required: true,
        },
        {
          name: 'reason',
          type: 3,
          description: 'Reason for ban',
          required: false,
        },
      ],
    },
    {
      name: 'mute',
      description: 'Mute a user',
      options: [
        {
          name: 'user',
          type: 6,
          description: 'User to mute',
          required: true,
        },
        {
          name: 'duration',
          type: 4, // INTEGER
          description: 'Duration in minutes',
          required: true,
        },
      ],
    },
  ];
  
  try {
    await client.application.commands.set(commands);
    console.log('✅ Slash commands registered');
  } catch (error) {
    console.error('❌ Failed to register commands:', error);
  }
  
  // Notify Central Hub that bot is ready
  try {
    await axios.post(\`\${process.env.CENTRAL_HUB_API_URL}/api/discord/bots/\${process.env.BOT_ID}/status\`, {
      status: 'running',
      guilds: client.guilds.cache.map(g => ({ id: g.id, name: g.name, memberCount: g.memberCount })),
    });
  } catch (error) {
    console.error('Failed to notify Central Hub:', error.message);
  }
});

// Handle interactions (slash commands)
client.on(Events.InteractionCreate, async (interaction) => {
  if (!interaction.isChatInputCommand()) return;
  
  const { commandName } = interaction;
  
  try {
    switch (commandName) {
      case 'help':
        await interaction.reply({
          content: \`🤖 **\${client.user.username}**\\\\n\\\\n**Commands:**\\\\n/help - Show this message\\\\n/status - Show bot status\\\\n/ask <question> - Ask AI a question\\\\n/kick @user [reason] - Kick a user\\\\n/ban @user [reason] - Ban a user\\\\n/mute @user <minutes> - Mute a user\`,
          ephemeral: true,
        });
        break;
        
      case 'status':
        const uptime = Math.floor(process.uptime() / 60);
        await interaction.reply({
          content: \`🟢 **Online**\\\\nUptime: \${uptime} minutes\\\\nServers: \${client.guilds.cache.size}\\\\nMemory: \${Math.floor(process.memoryUsage().heapUsed / 1024 / 1024)}MB\`,
          ephemeral: true,
        });
        break;
        
      case 'ask':
        if (!process.env.AI_ENABLED === 'true') {
          await interaction.reply({ content: '❌ AI is not enabled', ephemeral: true });
          return;
        }
        
        const question = interaction.options.getString('question');
        await interaction.deferReply();
        
        try {
          // Call Ollama for AI response
          const response = await axios.post(\`\${process.env.OLLAMA_HOST}/api/generate\`, {
            model: 'llama3.1:8b',
            prompt: question,
            stream: false,
          });
          
          await interaction.editReply(response.data.response.substring(0, 2000));
        } catch (error) {
          await interaction.editReply('❌ Failed to get AI response');
        }
        break;
        
      case 'kick':
        if (!interaction.memberPermissions.has('KickMembers')) {
          await interaction.reply({ content: '❌ You do not have permission to kick members', ephemeral: true });
          return;
        }
        
        const kickUser = interaction.options.getMember('user');
        const kickReason = interaction.options.getString('reason') || 'No reason provided';
        
        if (kickUser) {
          await kickUser.kick(kickReason);
          await interaction.reply(\`👢 Kicked \${kickUser.user.tag} for: \${kickReason}\`);
        }
        break;
        
      case 'ban':
        if (!interaction.memberPermissions.has('BanMembers')) {
          await interaction.reply({ content: '❌ You do not have permission to ban members', ephemeral: true });
          return;
        }
        
        const banUser = interaction.options.getMember('user');
        const banReason = interaction.options.getString('reason') || 'No reason provided';
        
        if (banUser) {
          await banUser.ban({ reason: banReason });
          await interaction.reply(\`🔨 Banned \${banUser.user.tag} for: \${banReason}\`);
        }
        break;
        
      case 'mute':
        if (!interaction.memberPermissions.has('ModerateMembers')) {
          await interaction.reply({ content: '❌ You do not have permission to mute members', ephemeral: true });
          return;
        }
        
        const muteUser = interaction.options.getMember('user');
        const duration = interaction.options.getInteger('duration');
        
        if (muteUser) {
          await muteUser.timeout(duration * 60 * 1000, \`Muted for \${duration} minutes\`);
          await interaction.reply(\`🔇 Muted \${muteUser.user.tag} for \${duration} minutes\`);
        }
        break;
    }
  } catch (error) {
    console.error(\`Error handling command \${commandName}:\`, error);
    await interaction.reply({ content: '❌ An error occurred', ephemeral: true });
  }
});

// Handle messages (for custom commands)
client.on(Events.MessageCreate, async (message) => {
  if (message.author.bot) return;
  
  // Update message count
  try {
    await axios.post(\`\${process.env.CENTRAL_HUB_API_URL}/api/discord/bots/\${process.env.BOT_ID}/metrics\`, {
      messages: 1,
    });
  } catch (error) {
    // Silently fail
  }
  
  // Check for custom commands
  const customCommands = config.customCommands || [];
  for (const cmd of customCommands) {
    if (message.content.toLowerCase() === \`\${config.prefix || '!'}\${cmd.name}\`.toLowerCase()) {
      await message.reply(cmd.response);
      return;
    }
  }
});

// Handle errors
client.on(Events.Error, async (error) => {
  console.error('Discord client error:', error);
  
  try {
    await axios.post(\`\${process.env.CENTRAL_HUB_API_URL}/api/discord/bots/\${process.env.BOT_ID}/error\`, {
      error: error.message,
    });
  } catch (e) {
    // Fail silently
  }
});

// Login
client.login(process.env.DISCORD_TOKEN);

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('SIGTERM received, shutting down gracefully');
  client.destroy();
  process.exit(0);
});
`;
}

/**
 * Generate command handlers code
 */
function generateCommandsCode(bot: DiscordBot): string {
  return `/**
 * Command Handlers
 * Bot: ${bot.name}
 */

const { SlashCommandBuilder } = require('discord.js');

function loadCommands(client) {
  // Built-in commands are handled in main file
  // Custom commands can be added here
  console.log('Commands loaded');
}

module.exports = { loadCommands };
`;
}

/**
 * Start a Discord bot
 */
export async function startBot(botId: string): Promise<boolean> {
  const bot = await prisma.discordBot.findUnique({
    where: { id: botId },
  });

  if (!bot) {
    throw new Error('Bot not found');
  }

  const botDir = path.join(BOTS_DIR, botId);

  try {
    // Check if already running
    if (bot.status === 'running') {
      console.log(`Bot ${bot.name} is already running`);
      return true;
    }

    // Install dependencies
    console.log(`📦 Installing dependencies for ${bot.name}...`);
    await execAsync('npm install', { cwd: botDir });

    // Start bot as separate process
    console.log(`🚀 Starting bot: ${bot.name}`);
    const process = exec('npm start', { cwd: botDir });

    // Store process info
    await prisma.discordBot.update({
      where: { id: botId },
      data: {
        status: 'running',
        processId: process.pid?.toString(),
      },
    });

    // Handle process output
    process.stdout?.on('data', (data) => {
      console.log(`[${bot.name}] ${data}`);
    });

    process.stderr?.on('data', (data) => {
      console.error(`[${bot.name}] ERROR: ${data}`);
    });

    process.on('exit', async (code) => {
      console.log(`Bot ${bot.name} exited with code ${code}`);
      await prisma.discordBot.update({
        where: { id: botId },
        data: { status: code === 0 ? 'stopped' : 'error' },
      });
    });

    return true;
  } catch (error) {
    console.error(`Failed to start bot ${bot.name}:`, error);
    
    await prisma.discordBot.update({
      where: { id: botId },
      data: {
        status: 'error',
        lastError: error instanceof Error ? error.message : 'Unknown error',
      },
    });
    
    return false;
  }
}

/**
 * Stop a Discord bot
 */
export async function stopBot(botId: string): Promise<boolean> {
  const bot = await prisma.discordBot.findUnique({
    where: { id: botId },
  });

  if (!bot) {
    throw new Error('Bot not found');
  }

  try {
    if (bot.processId) {
      // Kill the process
      process.kill(parseInt(bot.processId), 'SIGTERM');
    }

    await prisma.discordBot.update({
      where: { id: botId },
      data: {
        status: 'stopped',
        processId: null,
      },
    });

    console.log(`✅ Stopped bot: ${bot.name}`);
    return true;
  } catch (error) {
    console.error(`Failed to stop bot ${bot.name}:`, error);
    return false;
  }
}

/**
 * Update bot commands
 */
export async function updateCommands(
  botId: string,
  commands: Array<{ name: string; response: string }>
): Promise<DiscordBot> {
  const bot = await prisma.discordBot.findUnique({
    where: { id: botId },
  });

  if (!bot) {
    throw new Error('Bot not found');
  }

  const config = bot.configuration as any || {};
  config.customCommands = commands;

  const updated = await prisma.discordBot.update({
    where: { id: botId },
    data: {
      configuration: config,
    },
  });

  // Regenerate bot files
  await generateBotFiles(updated);

  console.log(`✅ Updated commands for bot: ${bot.name}`);
  return updated;
}

/**
 * Get bot status
 */
export async function getBotStatus(botId: string): Promise<BotStatus> {
  return withCache(
    async () => {
      const bot = await prisma.discordBot.findUnique({
        where: { id: botId },
      });

      if (!bot) {
        throw new Error('Bot not found');
      }

      // Try to fetch live status from bot's health endpoint (with circuit breaker)
      let liveStatus: any = {};
      try {
        liveStatus = await withDiscordCircuitBreaker(async () => {
          const response = await fetch(`http://localhost:3000/health`, {
            method: 'GET',
            headers: { 'Content-Type': 'application/json' },
          });
          if (response.ok) {
            return await response.json();
          }
          return {};
        });
      } catch {
        // Bot health endpoint not available, use cached data
      }

      return {
        status: bot.status as any,
        messageCount: bot.messageCount,
        errorCount: bot.errorCount,
        lastError: bot.lastError || undefined,
        guilds: [], // Would be populated from live status
        ...liveStatus,
      };
    },
    () => `discord:status:${botId}`,
    30 // 30 second cache for live status
  )();
}

/**
 * Send message through bot
 */
export async function sendMessage(
  botId: string,
  channelId: string,
  message: string
): Promise<boolean> {
  try {
    await fetch(`http://localhost:3000/webhook`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'send',
        channelId,
        message,
      }),
    });
    return true;
  } catch (error) {
    console.error('Failed to send message:', error);
    return false;
  }
}

/**
 * Delete a bot
 */
export async function deleteBot(botId: string): Promise<boolean> {
  const bot = await prisma.discordBot.findUnique({
    where: { id: botId },
  });

  if (!bot) {
    return false;
  }

  // Stop if running
  if (bot.status === 'running') {
    await stopBot(botId);
  }

  // Delete files
  const botDir = path.join(BOTS_DIR, botId);
  try {
    await rm(botDir, { recursive: true, force: true });
  } catch {
    // Ignore errors
  }

  // Delete from DB
  await prisma.discordBot.delete({
    where: { id: botId },
  });

  console.log(`✅ Deleted bot: ${bot.name}`);
  return true;
}

/**
 * Update bot configuration
 */
export async function updateBotConfiguration(
  botId: string,
  config: Partial<BotConfiguration>
): Promise<DiscordBot> {
  const bot = await prisma.discordBot.findUnique({
    where: { id: botId },
  });

  if (!bot) {
    throw new Error('Bot not found');
  }

  const currentConfig = bot.configuration as any || {};
  const updatedConfig = { ...currentConfig, ...config };

  const updated = await prisma.discordBot.update({
    where: { id: botId },
    data: {
      configuration: updatedConfig,
      aiEnabled: config.aiEnabled ?? bot.aiEnabled,
    },
  });

  // Regenerate bot files
  await generateBotFiles(updated);

  // Restart if running
  if (bot.status === 'running') {
    await stopBot(botId);
    await startBot(botId);
  }

  return updated;
}

/**
 * Get all bots
 */
export async function getAllBots(): Promise<DiscordBot[]> {
  return prisma.discordBot.findMany({
    orderBy: { createdAt: 'desc' },
  });
}

/**
 * Deploy bot to Railway (for persistent hosting)
 */
export async function deployBotToRailway(botId: string): Promise<boolean> {
  const bot = await prisma.discordBot.findUnique({
    where: { id: botId },
  });

  if (!bot) {
    throw new Error('Bot not found');
  }

  // This would create a new Railway service for the bot
  // Implementation depends on Railway API integration
  console.log(`📦 Deploying bot ${bot.name} to Railway...`);
  
  // TODO: Implement Railway deployment
  // 1. Create new service in Railway
  // 2. Deploy bot code
  // 3. Link service ID to bot record

  return true;
}

// Export service functions
export const discordService = {
  createBot,
  startBot,
  stopBot,
  updateCommands,
  getBotStatus,
  sendMessage,
  deleteBot,
  updateBotConfiguration,
  getAllBots,
  deployBotToRailway,
};

export default discordService;
